---
spring:
  profiles: prod

yojna:
  application: Yojna - IQI
  dbConnection:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    uname: hr
    password: sunil
  hibernate:
      showSql: false
      hbm2dll: validate
      dialect: org.hibernate.dialect.Oracle10gDialect